name: Run QA Integration Tests
"on":
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Cypress
        uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Check Cypress cache
        run: |
          npx cypress cache path
          npx cypress cache list

      - name: restore / cache the binary
        id: cache-cypress
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: >-
            cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json')
            }}

      - name: Install Cypress
        run: |
          npx cypress install
          npx cypress cache list

      - name: Run Cypress
        run: npm run cy:run

      - name: Generate Mochawesome report
        if: always()
        run: |
          npm run report:merge
          npm run report:generate

      - name: Commit report results
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./index.html -f
          git commit -m "[chore] autogenerate Mochawesome report" -a

      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          force: true
